language: ruby
rvm:
  - jruby-19mode-1.7.4
jdk: openjdk7
services:
  - redis
  - rabbitmq
before_script:
  - cp config/database.example.yml config/database.yml
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'
script: bundle exec rspec spec
